[project]
name = "search-for-mz-pubchem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pubchempy>=1.0.4",
    "rdkit>=2025.3.5",
]
